### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by GuySartorelli**
## Commits
1. Add an option so we can run just a single script. Useful if for example someone updated all the crons on the next-minor branch, but you need to run a new script on the next-patch branch :p
1. Start from scratch when updating PRs. This means if there are changes in the previous PR that shouldn't be applied, you can rerun with --update-prs and it will remove those changes before running the scripts.
1. Add the new workflow if there's a `action-ci.yml` file, since gha-* repos don't have `ci.yml`
1. Added exclusions for modules that shouldn't get the new workflow
1. Fix bug where repos with wildcard mapping for CMS major wouldn't run again the next-patch branch

## Issue
- https://github.com/silverstripe/gha-ci/issues/137

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Please exclude the following modules from getting the workflow in the future, which have open PRs:
- cow
- module-standardiser
- silverstripe-tx-translator
- supported-modules
- api.silverstripe.org

Ditto for the following that have closed PRs:
- webpack-config
- silverstripe-userhelp-content
- silverstripe-simple

Also ensure any other "tooling" repos where you may have already deleted the PR is excluded

**Comment by GuySartorelli** [comment]
The ones with closed prs arw already excluded, that's why I closed the prs.

**Comment by GuySartorelli** [comment]
Added exclusions.

**Review by emteknetnz — APPROVED** [review]

**Comment by GuySartorelli** [comment]
Added an extra commit to fix a bug where repos with wildcard mapping for CMS major wouldn't run again the next-patch branch

**Pull request merged**
